workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
      xcode: latest
    scripts:
      - name: Force Kotlin 1.9.22
        script: |
          cd android
          echo "kotlinVersion=1.9.22" >> gradle.properties
          echo "kotlin.jvm.target=1.8" >> gradle.properties
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk